name: Build PDF Merger Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --noconsole --onefile --name "PDF-Merger" merge_pdfs.py
        
    - name: Build executable (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --noconsole --onefile --windowed --name "PDF-Merger" merge_pdfs.py
        
    - name: Build executable (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libxcb-xinerama0
        pyinstaller --onefile --name "PDF-Merger" merge_pdfs.py
        
    - name: Upload artifacts (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: PDF-Merger-Windows
        path: dist/PDF-Merger.exe
        
    - name: Upload artifacts (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v3
      with:
        name: PDF-Merger-macOS
        path: dist/PDF-Merger
        
    - name: Upload artifacts (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: PDF-Merger-Linux
        path: dist/PDF-Merger

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      
    - name: Create release assets
      run: |
        zip -r PDF-Merger-Windows.zip PDF-Merger-Windows/
        tar -czf PDF-Merger-macOS.tar.gz PDF-Merger-macOS/
        tar -czf PDF-Merger-Linux.tar.gz PDF-Merger-Linux/
        
    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          PDF-Merger-Windows.zip
          PDF-Merger-macOS.tar.gz
          PDF-Merger-Linux.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}